version: 2.0
jobs:
  deploy:
    docker:
      - image: circleci/command-convenience:0.1
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
        environment:
          NAME: postgres-script-enhance
          CONTAINER_ORG: circleci
          DOCKERFILE_PATH: Dockerfile
          DOCKER_REGISTRY: dockerhub

    working_directory: /home/circleci/postgres

    steps:
      - checkout

      - setup_remote_docker

      - run: publish

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
